# PIPELINES IN SCIKIT LEARN

**The core idea (intuition):**

In real ML workflows, you almost always do this:

- Preprocess data

- scaling

- encoding

- imputing missing values

- Train a model

**A pipeline guarantees:**

- Steps happen in the correct order

- The same preprocessing is applied to train and test data

- No data leakage

- Cleaner code

-> **PIPELINES MAKES IT EASY TO APPLY THE SAME PREPROCESSING TO TRAIN AND TEST**

scaler = StandardScaler() <br>
X_train_scaled = scaler.fit_transform(X_train)<br>
X_test_scaled = scaler.fit_transform(X_test)  # ❌ WRONG (data leakage)<br>
<br>
model.fit(X_train_scaled, y_train)

# Where does data leakage happen?

Now look at this:

scaler.fit_transform(X_test)


This means:

You are recalculating mean & std using test data

The model indirectly gets information about the test set

👉 This breaks the rule:

Test data must be completely unseen during training

Even though you’re not fitting the model, you’re still learning from test data.

That is data leakage.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = sns.load_dataset('titanic')
df = df.iloc[:, :8]
df

survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(columns = ['survived']), df['survived'], test_size = 0.2, random_state = 42)

In [4]:
X_train.head(2)

pclass   sex   age  sibsp  parch  fare embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [5]:
Y_train.head(2)

331    0
733    0
Name: survived, dtype: int64

In [6]:
df.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

In [7]:
si_age = SimpleImputer(strategy='mean')
si_embarked = SimpleImputer(strategy = 'most_frequent')

X_train_age = si_age.fit_transform(X_train[['age']])
X_train_embarked = si_embarked.fit_transform(X_train[['embarked']])

X_test_age = si_age.transform(X_test[['age']])
X_test_embarked = si_embarked.transform(X_test[['embarked']])

In [8]:
X_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

In [9]:
# one hot encoding
oe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
oe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')


X_train_sex = oe_sex.fit_transform(X_train[['sex']])
X_train_embarked = oe_embarked.fit_transform(X_train_embarked)

X_test_sex = oe_sex.transform(X_test[['sex']])
X_test_embarked = oe_embarked.transform(X_test_embarked)

In [10]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], shape=(712, 2))

In [11]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(712, 3))

In [12]:
X_train

pclass     sex   age  sibsp  parch      fare embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [13]:
X_train_rem = X_train.drop(columns= ['sex', 'age', 'embarked'])
X_test_rem = X_test.drop(columns=['sex', 'age', 'embarked'])

In [15]:
X_train_transformed = np.concatenate((X_train_rem, X_train_sex, X_train_age, X_train_embarked), axis = 1)
X_test_transformed = np.concatenate((X_test_rem, X_test_sex, X_test_age, X_test_embarked), axis = 1)

In [16]:
X_train_transformed.shape

(712, 10)

In [18]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, Y_train)

DecisionTreeClassifier()

In [19]:
y_pred = clf.predict(X_test_transformed)

In [20]:
from sklearn.metrics import accuracy_score

In [22]:
accuracy_score(Y_test, y_pred)

0.7821229050279329